from pathlib import Path
import re

INDEX = Path("index.html")
html = INDEX.read_text(encoding="utf-8")


def replace_all(old: str, new: str) -> None:
    global html
    html = html.replace(old, new)


# ---------------------------------------------------------------------------
# 1. Keep profile positioning consistent with the resume / LinkedIn wording.
# ---------------------------------------------------------------------------
replace_all("16+ anos no setor financeiro", "15+ anos no setor financeiro")
replace_all("16+ years in financial services", "15+ years in financial services")
replace_all("com 16 anos de experiência no setor financeiro", "com mais de 15 anos de experiência no setor financeiro")
replace_all("with 16 years of experience in the financial sector", "with 15+ years of experience in the financial sector")
replace_all(
    "⚡ 100% Autonomously Generated by Squad Forge SE via Local LLM",
    "⚡ Built with Squad Forge SE — my autonomous software engineering platform using a local model",
)

# The CV buttons currently open HTML documents, not PDFs.
replace_all('fa-solid fa-file-pdf', 'fa-solid fa-file-lines')

# ---------------------------------------------------------------------------
# 2. Mark the three strongest cross-role projects as recruiter-facing Featured.
#    This keeps all seven projects visible while creating a fast scanning path.
# ---------------------------------------------------------------------------
replace_all(
    '>Autonomous AI OS</span>',
    '>Featured • AI Engineering</span>',
)
replace_all(
    '>Generative AI & Health</span>',
    '>Featured • Agentic RAG</span>',
)
replace_all(
    '>FinTech & Anti-Fraud</span>',
    '>Featured • ML/MLOps</span>',
)

# ---------------------------------------------------------------------------
# 3. time_series_predict — align with the current quantitative platform README.
# ---------------------------------------------------------------------------
replace_all(
    "Suíte completa de previsão de séries temporais não-lineares e de alta volatilidade combinando redes neurais profundas (LSTMs, GRUs, Transformers) e modelagem econométrica clássica (SARIMAX), desenvolvida para a disciplina MIT-510 do Mestrado em IA (AGTU).",
    "Plataforma quantitativa de séries temporais com validação walk-forward purgada, LightGBM/XGBoost, BiLSTM com atenção, TCN e stacking, além de backtesting com custos, slippage e métricas de risco.",
)
replace_all(
    "Comprehensive time-series forecasting suite for non-linear, high-volatility data combining Deep Learning (LSTMs, GRUs, Transformers) and econometric modeling (SARIMAX), developed for MIT-510 in the MSc in AI program (AGTU).",
    "Quantitative time-series platform with purged walk-forward validation, LightGBM/XGBoost, attention-based BiLSTM, TCN and stacking, plus event-driven backtesting with costs, slippage and risk metrics.",
)
replace_all("Modelagem Híbrida & Benchmarks Estatísticos", "Sharpe 1,42 • Hit Rate 56,8% • Purged CV")
replace_all("Hybrid Modeling & Statistical Benchmarks", "Sharpe 1.42 • Hit Rate 56.8% • Purged CV")
replace_all(
    '<span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">Statsmodels</span>\n              <span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">SciPy</span>\n              <span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">Pandas</span>',
    '<span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">LightGBM</span>\n              <span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">XGBoost</span>\n              <span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">FastAPI</span>',
)

# ---------------------------------------------------------------------------
# 4. ontology_rag_guardrail — preserve the repository's explicit experimental
#    boundary and emphasize EVALs, trivalent decisions and auditability.
# ---------------------------------------------------------------------------
replace_all(
    "Framework de governança semântica e RAG governado por ontologias e Grafos de Conhecimento (Neo4j) para mitigar alucinações e proteger aplicações de LLMs em ambientes corporativos altamente regulados.",
    "SDK/runtime experimental para governança semântica de LLMs, RAG e agentes, com EVALs, observabilidade, decisões trivalentes (TRUE/FALSE/UNDECIDABLE), proveniência e registros de prova auditáveis.",
)
replace_all(
    "Enterprise semantic governance and RAG framework governed by ontologies and Knowledge Graphs (Neo4j) to eliminate hallucinations and protect corporate LLM pipelines.",
    "Experimental SDK/runtime for semantic governance of LLM, RAG and agent systems, with EVALs, observability, trivalent decisions (TRUE/FALSE/UNDECIDABLE), provenance and auditable proof records.",
)
replace_all("Graph RAG & Validação Determinística OWL", "96-case EVAL benchmark • TRUE/FALSE/UNDECIDABLE")
replace_all("Graph RAG & Deterministic OWL Validation", "96-case EVAL benchmark • TRUE/FALSE/UNDECIDABLE")
replace_all(
    '<span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">LangChain</span>\n              <span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">Neo4j</span>\n              <span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">Graph RAG</span>\n              <span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">Pydantic</span>',
    '<span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">FastAPI</span>\n              <span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">RAG EVALs</span>\n              <span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">Ontologies</span>\n              <span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">Auditability</span>',
)

# ---------------------------------------------------------------------------
# 5. rag_agent_datasus — align with v2 LangGraph + hybrid RAG implementation.
# ---------------------------------------------------------------------------
replace_all(
    "Agente inteligente RAG para análise epidemiológica e inteligência em vigilância de saúde pública a partir de dados do Datasus (SRAG), desenvolvido e premiado no Desafio Indicium AI para Engenheiro de IA.",
    "Sistema de inteligência epidemiológica sobre 473 mil+ registros do DataSUS, com orquestração multi-agente em LangGraph, RAG híbrido ChromaDB + BM25/RRF, embeddings locais, guardrails e observabilidade auditável.",
)
replace_all(
    "Intelligent RAG agent for public health data analytics and epidemiological surveillance using Datasus (SRAG) datasets, awarded in the Indicium AI Challenge for AI Engineers.",
    "Epidemiological intelligence system over 473k+ DataSUS records with LangGraph multi-agent orchestration, hybrid ChromaDB + BM25/RRF retrieval, local embeddings, guardrails and auditable observability.",
)
replace_all("Desafio Indicium AI & Vector Search", "473.791 registros • Faithfulness 98% • MRR 0,88")
replace_all("Indicium AI Challenge & Vector Search", "473,791 records • Faithfulness 98% • MRR 0.88")
replace_all(
    '<span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">LlamaIndex</span>\n              <span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">ChromaDB</span>\n              <span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">FastAPI</span>\n              <span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">Streamlit</span>',
    '<span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">LangGraph</span>\n              <span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">ChromaDB</span>\n              <span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">BM25 / RRF</span>\n              <span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">Streamlit</span>',
)

# ---------------------------------------------------------------------------
# 6. credit_scoring_model / PRINAD — current repository is broader than a
#    classic scorecard and includes Champion/Challenger, macro stress and EVALs.
# ---------------------------------------------------------------------------
replace_all(
    "Construção e calibração estatística de scorecards de crédito bancário com Weight of Evidence (WoE), Information Value (IV), regressão logística regularizada e métricas de discriminação (KS, AUC-ROC, Gini).",
    "Motor PRINAD de risco de crédito com Champion regulatório WoE + regressão logística e Challengers LightGBM/XGBoost/Stacking, calibração, stress de Vasicek, IFRS 9, RAROC e Continuous EVALs.",
)
replace_all(
    "Statistical credit scorecard development and probability of default calibration with Weight of Evidence (WoE), Information Value (IV), regularized logistic regression, and KS/AUC metrics.",
    "PRINAD credit-risk engine with a regulatory WoE + logistic-regression Champion and LightGBM/XGBoost/Stacking Challengers, calibration, Vasicek stress, IFRS 9, RAROC and Continuous EVALs.",
)
replace_all("Weight of Evidence (WoE) & KS Calibração", "ROC-AUC 0,9818 • Gini 0,9637 • KS 0,8627")
replace_all("Weight of Evidence (WoE) & KS Calibration", "ROC-AUC 0.9818 • Gini 0.9637 • KS 0.8627")
replace_all(
    '<span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">Scikit-Learn</span>\n              <span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">Statsmodels</span>\n              <span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">Pandas</span>\n              <span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">NumPy</span>',
    '<span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">LightGBM</span>\n              <span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">XGBoost</span>\n              <span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">IFRS 9</span>\n              <span class="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">FastAPI</span>',
)
replace_all("FinTech & Scorecards", "FinTech & Credit Risk")
replace_all("Statistical Scoring", "Champion / Challenger")

# ---------------------------------------------------------------------------
# 7. Career assistant UX: keep questions fully free-form, but prevent accidental
#    concurrent requests and make optional Worker sources clickable.
# ---------------------------------------------------------------------------
replace_all(
    "const url = source.url ? ` (${source.url})` : '';\n                  return `- ${label}${url}`;",
    "if (source.url) return `- [${label}](${source.url})`;\n                  return `- ${label}`;",
)

start_anchor = "    async function processQuestion(question) {\n      appendMessage('user', question, false);"
start_replacement = "    async function processQuestion(question) {\n      chatSubmitBtn.disabled = true;\n      chatInput.disabled = true;\n      chatBox.setAttribute('aria-busy', 'true');\n      appendMessage('user', question, false);"
replace_all(start_anchor, start_replacement)

end_anchor = "      conversationHistory.push({ role: 'assistant', content: rawAssistantReply || '' });\n      appendMessage('ai', answer, true);\n    }"
end_replacement = "      conversationHistory.push({ role: 'assistant', content: rawAssistantReply || '' });\n      appendMessage('ai', answer, true);\n      chatBox.setAttribute('aria-busy', 'false');\n      chatInput.disabled = false;\n      chatSubmitBtn.disabled = false;\n      chatInput.focus();\n    }"
replace_all(end_anchor, end_replacement)

# Remove the old substantive deterministic profile-summary FAQ entirely. It was
# already bypassed, but deleting it makes the architecture unambiguous to reviewers.
pattern = re.compile(
    r"\n      \{\n        triggers: \[\n          \"quem e o adilio\".*?\n        \}\n      \},(?=\n      \{\n        utility: true,)",
    re.S,
)
html, _ = pattern.subn("", html, count=1)

INDEX.write_text(html, encoding="utf-8")
print("Applied final recruiter-facing evidence and UX patch.")
